/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedAiQualityRouteImport } from './routes/_protected.ai-quality'
import { Route as ProtectedMyCasesRouteImport } from './routes/_protected.my-cases'
import { Route as ProtectedQueueRouteImport } from './routes/_protected.queue'
import { Route as ProtectedCasesCaseIdRouteImport } from './routes/_protected.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAiQualityRoute = ProtectedAiQualityRouteImport.update({
  id: '/ai-quality',
  path: '/ai-quality',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyCasesRoute = ProtectedMyCasesRouteImport.update({
  id: '/my-cases',
  path: '/my-cases',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQueueRoute = ProtectedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCasesCaseIdRoute = ProtectedCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-quality': typeof ProtectedAiQualityRoute
  '/my-cases': typeof ProtectedMyCasesRoute
  '/queue': typeof ProtectedQueueRoute
  '/cases/$caseId': typeof ProtectedCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-quality': typeof ProtectedAiQualityRoute
  '/my-cases': typeof ProtectedMyCasesRoute
  '/queue': typeof ProtectedQueueRoute
  '/cases/$caseId': typeof ProtectedCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/ai-quality': typeof ProtectedAiQualityRoute
  '/_protected/my-cases': typeof ProtectedMyCasesRoute
  '/_protected/queue': typeof ProtectedQueueRoute
  '/_protected/cases/$caseId': typeof ProtectedCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/ai-quality' | '/my-cases' | '/queue' | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/ai-quality' | '/my-cases' | '/queue' | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/ai-quality'
    | '/_protected/my-cases'
    | '/_protected/queue'
    | '/_protected/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/ai-quality': {
      id: '/_protected/ai-quality'
      path: '/ai-quality'
      fullPath: '/ai-quality'
      preLoaderRoute: typeof ProtectedAiQualityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-cases': {
      id: '/_protected/my-cases'
      path: '/my-cases'
      fullPath: '/my-cases'
      preLoaderRoute: typeof ProtectedMyCasesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/queue': {
      id: '/_protected/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof ProtectedQueueRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cases/$caseId': {
      id: '/_protected/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof ProtectedCasesCaseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAiQualityRoute: typeof ProtectedAiQualityRoute
  ProtectedMyCasesRoute: typeof ProtectedMyCasesRoute
  ProtectedQueueRoute: typeof ProtectedQueueRoute
  ProtectedCasesCaseIdRoute: typeof ProtectedCasesCaseIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAiQualityRoute: ProtectedAiQualityRoute,
  ProtectedMyCasesRoute: ProtectedMyCasesRoute,
  ProtectedQueueRoute: ProtectedQueueRoute,
  ProtectedCasesCaseIdRoute: ProtectedCasesCaseIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
